# Updated experimental settings, required to run perceiver models

name = "transformer_test" # experiment name - should be the same as file name
compile = true

[data]
n_workers = 4

[scheduler]
warm_up_epochs = 5

[optimiser]
class = "AdamW"
weight_decay = 0.1
clip_grad_norm = 1.0

[sender]
feature_model = "ViT2"
vision_dropout = 0.0

[sender_feature_model]
d_model = 32 # Only applies to Transformer vision models
layers = 4 # Only applies to Transformer vision models
heads = 4 # Only applies to Transformer vision models
utility_tokens = 0 # Only applies to Transformer vision models

[receiver]
feature_model = "ViT2"
vision_dropout = 0.1

[receiver_feature_model]
d_model = 32 # Only applies to Transformer vision models
layers = 4 # Only applies to Transformer vision models
heads = 4 # Only applies to Transformer vision models
utility_tokens = 0 # Only applies to Transformer vision models