# Updated experimental settings, required to run perceiver models

name = "vit_speed_test" # experiment name - should be the same as file name

[data]
batch_size = 16

[optimiser]
class = "AdamW"
accumulator_steps = 4

[scheduler]
epochs = 1

[sender.arguments]
image_encoder = "tiny_vit"

[receiver.arguments]
image_encoder = "tiny_vit"